### PR TITLE
Fix bugs & make compatible for old k8s server version.

### PR DESCRIPTION
**Pull request by kocomic**

### CODE REVIEW

**Comment by kocomic** [comment]
While cluster is updating, job will be recreate, this may consuming too much cluster resources(jobs terminating need time).
Fix submitter job spawn while updating job cluster (https://github.com/spotify/flink-on-k8s-operator/issues/399).
Disable PodDisruptionBudget when k8s server version <v1.21(https://github.com/spotify/flink-on-k8s-operator/issues/381).
Fix component checks for cluster update and taskmanager deployments.

**Review by regadas — COMMENTED** [review]
Sorry for late reply here @kocomic and thanks for this. I think you address some interesting things and I have a couple of requests if you don't mind 😄. 

Could you rebase your branch and split your fixes in different PR's?

Thanks

**Comment by kocomic** [comment]
OK, thanks for reply ,I' ll split changes later.

**Comment by GilShmaya** [comment]
Hi, is that fix would be merged soon?

**Comment by kocomic** [comment]
will split and tested this weekend :)

**Comment by DivineDX** [comment]
> will split and tested this weekend :)

Hi @kocomic, could I kindly check if there are any updates for this?

**Comment by kocomic** [comment]
> 

Sorry for the late cause of personal problems (job-hopping). I had splited this pr to 2 prs (Disable PDB under k8s version <= 1.21 & Fixed taskManager related checks.). And the job spawn fix require more test (reappeared in my production env).

**Pull request closed without merging**
