### PR TITLE
Upgrade to Golang 1.18

### PR DESCRIPTION
**Pull request by haoxins**
as https://github.com/spotify/flink-on-k8s-operator/pull/325

### CODE REVIEW

**Review by regadas — COMMENTED** [review]
Thanks for this @haoxins;

What was the reason behind the change of the `Makefile`?

**Comment by haoxins** [comment]
the `go get` is deprecated for `Go 1.18`, replaced with `go install`

**Comment by regadas** [comment]
gotcha but why not just change this line?

```
GOBIN=$(PROJECT_DIR)/bin go get $(2)
```

**Comment by haoxins** [comment]
> gotcha but why not just change this line?
> 
> ```
> GOBIN=$(PROJECT_DIR)/bin go get $(2)
> ```

updated

**Review by regadas — APPROVED** [review]
Thanks for this @haoxins; I reverted the Makefile coz it's working ok and I postponed the `any` type change. Hope you don't mind 🙏

**Pull request merged**
