### PR TITLE
Allow JM to have more than 1 replicas

### LINKED ISSUE #256: Error setting up HA for JobManager
Flink supports [HA for the job manager ](https://nightlies.apache.org/flink/flink-docs-release-1.14/docs/deployment/ha/overview/#high-availability-services). I tried to configure it in my cluster but doesn't seem I can set more than one replica for the JobManager. When I try to do so I get the following error:
`for: "k8s/metrics-aggregator.yaml": admission webhook "vflinkcluster.flinkoperator.k8s.io" denied the request: invalid JobManager replicas, it must be 1
`

This is an excerpt of my descriptor:
`
spec:
  flinkVersion: "1.13"
  image:
    name: docker.atl-paas.net/atlassian/innoweek-flink-k8s:0.0.0
  jobManager:
    podAnnotations:
      iam.amazonaws.com/role: arn:aws:iam::XXXXXXXXXX:role/sfarsaci-flink-k8s-dev
    accessScope: Cluster
    replicas: 3
`
Is HA for the job manager possible using `flink-on-k8s-operator` or am I doing something wrong?

### PR DESCRIPTION
**Pull request by jto**
In a HA setup, one may want to have more than 1 JM replica.
fixes #256

### CODE REVIEW

**Comment by jto** [comment]
@martinbomio I'll need to test it on our dev cluster.

**Comment by regadas** [comment]
Hm, right... maybe we could just add the required props for HA automatically when setting replicas >1? keeping the default value as 1 and then be clear of the behavior in docs. wdyt?

**Comment by jto** [comment]
@regadas Yep that's what I was thinking too.

**Comment by martinbomio** [comment]
@jto @regadas do we have an issue to track this festure request? If we don't, I can create one given this is still relevant

**Comment by regadas** [comment]
I think this one is a bit related https://github.com/spotify/flink-on-k8s-operator/issues/256. But feel free to open a new one if you feel it doesn't capture it all.

**Pull request closed without merging**
